"""Phase C agent: LLM with a CVXPY solver tool.

Orchestrates the agentic EV charging workflow:
  1. The LLM receives the problem context (sessions, site cap, TOU rates)
     and the user request as a natural-language message.
  2. The LLM decides whether to call 'solve_ev_schedule':
       - Scheduling / optimization requests → tool is called.
       - What-if / constraint-change requests → tool is called with overrides
         (disabled_chargers, site_cap_kw, extra_sessions).
       - Qualitative / conceptual questions → LLM answers directly; no tool call.
  3. If the tool was called, the LLM uses the returned metrics to explain the
     outcome. If not, the LLM's direct answer is used as the explanation.
  4. The runner validates the stored schedule and builds the AgentResult.

If the LLM does not call the tool, AgentResult.feasible is False and the
schedule is a zero matrix; the explanation still contains the LLM's answer.

For natural-language input (no pre-built DaySessions), use run_agent_from_text().
It first calls parse_nl_problem() to extract structured session data, then
runs the normal agent pipeline. If required fields are missing it returns a
ClarificationResult instead of an AgentResult.
"""

from dataclasses import dataclass
from typing import Optional, Union

import numpy as np

from agent.llm_agent import run_agent_llm
from config.site import SiteConfig, TOUConfig
from data.format.schema import DaySessions


@dataclass
class ClarificationResult:
    """Returned by run_agent_from_text() when required session fields are missing.

    Attributes:
        message: Human-readable question to present to the user so they can
            supply the missing information (e.g. arrival/departure times).
    """

    message: str


@dataclass
class AgentResult:
    """Result of running the agent pipeline.

    Attributes:
        schedule: Power schedule array of shape (n_sessions, n_steps) in kW.
        total_cost_usd: Total energy cost in USD.
        peak_load_kw: Maximum total power draw across all sessions (kW).
        unmet_energy_kwh: Total unmet energy across all sessions (kWh).
        feasible: True if the schedule satisfies all constraints.
        explanation: Human-readable summary generated by the LLM.
    """

    schedule: np.ndarray
    total_cost_usd: float
    peak_load_kw: float
    unmet_energy_kwh: float
    feasible: bool
    explanation: str


def run_agent(
    day: DaySessions,
    site: SiteConfig,
    tou: TOUConfig,
    request: str = "Minimize energy cost for this day.",
    max_retries: int = 1,
) -> AgentResult:
    """Run the LLM agent with CVXPY solver tool.

    Args:
        day: DaySessions with sessions and horizon.
        site: SiteConfig with power cap.
        tou: TOUConfig with TOU rates.
        request: Natural-language request sent to the LLM.
        max_retries: Passed through as max_tool_rounds; lets the LLM call the
            solver more than once if needed (default 1 → cap at 3 rounds).

    Returns:
        AgentResult with schedule, metrics, feasibility, and LLM explanation.
    """
    # max_retries maps to max_tool_rounds; add 2 to allow the LLM at least one
    # tool call plus a retry before the explanation turn.
    max_tool_rounds = max(3, max_retries + 2)

    (
        schedule,
        total_cost_usd,
        peak_load_kw,
        unmet_energy_kwh,
        feasible,
        explanation,
    ) = run_agent_llm(
        day,
        site,
        tou,
        request=request,
        max_tool_rounds=max_tool_rounds,
    )

    return AgentResult(
        schedule=schedule,
        total_cost_usd=total_cost_usd,
        peak_load_kw=peak_load_kw,
        unmet_energy_kwh=unmet_energy_kwh,
        feasible=feasible,
        explanation=explanation,
    )


def run_agent_from_text(
    user_text: str,
    *,
    model: str = "gpt-4o",
    api_key: Optional[str] = None,
    max_retries: int = 1,
) -> Union[AgentResult, ClarificationResult]:
    """Run the full agent pipeline from a natural-language problem description.

    This is the entry point for free-form user input. It performs two LLM calls:
      1. parse_nl_problem() — extracts structured session data (arrival, departure,
         energy, power) from the user's text. Returns a ClarificationResult if
         required fields are missing.
      2. run_agent_llm() — the existing agent loop that decides whether to call
         the CVXPY solver or answer directly.

    Args:
        user_text: Free-form natural-language description of the charging problem.
            Examples:
              "I have 3 EVs. EV1 arrives at 6pm, leaves at 10pm, needs 20 kWh.
               EV2 arrives at 7pm, leaves at 11pm, needs 15 kWh.
               EV3 arrives at 8pm, leaves at midnight, needs 10 kWh."
              "Minimize cost for two cars: one needs 25 kWh from 5pm to 9pm,
               one needs 12 kWh from 6pm to 10pm. Site cap is 30 kW."
        model: OpenAI model name (used for both the parse and agent calls).
        api_key: OpenAI API key (falls back to OPENAI_API_KEY env var).
        max_retries: Passed to run_agent() as max_retries.

    Returns:
        AgentResult if the problem was fully specified and the solver ran, or
        ClarificationResult if required session fields were missing.
    """
    from agent.parse.parse import parse_nl_problem, parsed_problem_to_day_site_tou

    parse_result = parse_nl_problem(user_text, model=model, api_key=api_key)

    if parse_result.needs_clarification:
        return ClarificationResult(message=parse_result.clarification_message)

    day, site, tou = parsed_problem_to_day_site_tou(parse_result.problem)  # type: ignore[arg-type]

    return run_agent(day, site, tou, request=user_text, max_retries=max_retries)
